name: scrape
on:
  workflow_run:
    workflows: ['pages-build-deployment']
    types: [completed]
    branches:
      - 'master'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Enable debug logs
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
      - name: Installed package list
        run: apt list --installed
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable -y && sudo apt update
      - name: Remove default Chromium
        run: sudo apt purge chromium-browser -y && sudo apt update
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser
      - name: Verify Chromium installation
        run: chromium-browser --version
      - name: Install all necessary packages
        run: pip install requests beautifulsoup4 pandas webdriver-manager selenium
      - name: Verify Python packages
        run: pip list
      - name: Run the scraping script
        run: python -u scraper.py
